name: Build Android APK
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Fix Config & Build
        run: |
          GRADLEW_PATH=$(find . -name "gradlew" | head -n 1)
          BUILD_DIR=$(dirname "$GRADLEW_PATH")
          cd "$BUILD_DIR"

          # 1. Xóa bỏ MaxPermSize gây lỗi trong toàn bộ project
          find . -name "*.gradle" -exec sed -i 's/-XX:MaxPermSize=[^ ]*//g' {} +
          find . -name "gradle.properties" -exec sed -i 's/-XX:MaxPermSize=[^ ]*//g' {} +
          
          # 2. Thay thế máy chủ Trung Quốc bằng kho chuẩn (như bước trước)
          find . -name "*.gradle" -exec sed -i 's/maven.aliyun.com/repo1.maven.org/g' {} +

          # 3. Cấp quyền và chạy build
          chmod +x ./gradlew
          ./gradlew assembleDebug --no-daemon
          
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: XPlan-APK
          path: "**/*.apk"
