name: Build Android APK
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: |
          # Đường dẫn chính xác của dự án này
          chmod +x frameworks/runtime-src/proj.android/gradlew || echo "Không tìm thấy gradlew"

      - name: Build with Gradle
        run: |
          cd frameworks/runtime-src/proj.android
          ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: XPlan-APK
          path: "frameworks/runtime-src/proj.android/app/build/outputs/apk/debug/*.apk"
